/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomLink: typeof import('./theme/components/CustomLink.vue')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
  }
}
